- src/components/button/Button.jsx
- src/components/button/Button.styles.js
- src/components/navigationBar/NavigationBar.jsx
- src/components/navigationBar/NavigationBar.styles.js
- src/pages/main/MainPage.styles.js
- src/pages/main/index.jsx
- 반응형 사이즈 수정
- 하단 버튼 길이 수정
- 내비게이션 바의 버튼 있고 없고
> 소개 페이지 반응형, 버튼들 수정

- src/Router.js
- src/pages/post/components/postCard/PostCardAdd.jsx
추가버튼 누를때 /post/id/message로 이동하게만 바꿨습니다 좀더 손봐야할꺼같네요
> ✨ 게시물 추가 버튼 누를시 /post/id/message로 이동하게만 설정

- public/assets/post-to/Enabled.svg
- src/Router.js
- src/components/button/Button.jsx
- src/components/button/Button.styles.js
- src/pages/post-to/PostToPage.styles.js
- src/pages/post-to/components/Card.jsx
- src/pages/post-to/components/Card.styles.js
- src/pages/post-to/index.jsx
- Post 작성 페이지 UI, 반응형
- 하단 버튼 반응형 수정
> Post 작성 페이지, 반응형, 하단 버튼 반응형 수정

- src/Router.js
- src/pages/post/components/MessageRecipient.jsx
- src/pages/post/components/PostPageMain.jsx
- src/pages/post/components/postCard/PostCardItem.jsx
- src/pages/post/components/postCard/api.js
- src/pages/post/index.jsx
> 페이퍼 받은사람 이름이 나타나도록 기능 추가

- package-lock.json
- package.json
- src/pages/post/components/postCard/PostCardItem.jsx
- src/pages/post/components/postCard/PostCardStyle.jsx
react-intersection-observe를 통해 무한스크롤을 구현했습니다(ItemCard.jsx)
```JSX
// ref: 화면에 나타났는지 찾을 요소 inView: 화면에 대상이 나타났는지 확인하는 bollean값
const [ref, inView] = useInView();
// api 요청 함수인 fetchData를 통해 inView가 true일 경우 사용자가 스크롤을 다 내렸다는 뜻이므로 api를 불러옵니다
// fetchData함수에서 offset의 값을 1씩 증가시켜 다음 데이터들을 불러올수 있게 했습니다. 
useEffect(() => {
if (inView) {
fetchData();
}
}, [inView]);
```
> ✨  react-intersection-observe를 통한 무한스크롤 기능 구현

- src/pages/post-to/components/profile/Profile.style.jsx
- src/pages/post-to/components/profile/Proifle.jsx
https://rolling-api.vercel.app/profile-images/ 를 통해 프로필 이미지 정보를 받아 선택 가능하게 함
> ✨ 프로필 이미지 선택 기능

- src/pages/post/components/postCard/DeleteButton.style.jsx
충돌해결하다가 지우지 못한부분때문에 오류가 생겼네요 해결해서 다시 pr합니다
> 오타로인한 오류 해결

- src/pages/post/index.jsx
- src/pages/post/index.style.jsx
#79 
배경 sticky로 어떻게 해보려다가 멘탈 나가서 
그냥 root relative div에다가 하위 div하나 만들어서 absolute박고 top:-10rem 먹이는 식으로 하드코딩했습니다.
일단 네비게이션 바에 top: -10rem 먹이니까 잘 작동하긴 하는데 실제 오버스크롤이 되는 환경에서는 모르겠네요
> 🐛 상단 오버스크롤 관련 문제 픽스? #79

- src/pages/post/components/PostPageMain/PostPageMain.jsx
- src/pages/post/components/postCard/DeleteButton.style.jsx
- 삭제하기 버튼이 오른쪽에 쭈구리고 있던 것 수정했어요
> 💄 모바일에서 버튼 작아지는 것 수정

- src/pages/post-to/components/post-to-card/Card.style.jsx
- src/pages/post-to/components/post-to-card/CardList.jsx
- src/pages/post-to/components/post-to-card/ImageCard.jsx
- src/pages/post-to/components/post-to-card/SkeletonUI.jsx
- src/pages/post-to/components/post-to-card/SkeletonUI.style.jsx
- src/pages/post-to/index.jsx
- 이미지 카드 인라인 스타일 제거
- 이미지 카드 컴포넌트 분리
- 이미지 카드 반응형 수정
- 스켈레톤 UI 적용 부분 코드 리팩토링
-
> [post-to] 이미지 인라인 스타일 제거, 코드 리팩토링

- src/GlobalStyles.js
- src/Router.js
- src/components/navigationBar/NavigationBar.jsx
- src/components/navigationBar/NavigationBar.style.jsx
- src/context/themeProvider.js
- src/pages/post/components/ShareDropdownModal/ShareDropdownModal.jsx
- src/theme/ThemeToggle.jsx
- src/theme/theme.js
- src/utils/shareKakao.js
- .env에 js키값 추가
- 연동되는 주소 배포된 주소로 변경( 변경시 수정)
- 공유하기 버튼에 shareKakao함수 추가
- 적용하고 배포된 주소에서 열면 잘 될겁니다..!
-
> [Post] 카카오톡 연동 수정

- src/pages/list/components/ArrowBtn/ArrowBtn.style.jsx
- src/pages/post-to/components/profile/PokemonProfileModal.jsx
- src/pages/post-to/components/profile/PokemonProfileModal.style.jsx
- src/pages/post-to/components/profile/Profile.style.jsx
- List 페이지 Arrow 버튼 커서 스타일링, 호버 상태 스타일링
- 프로필 이미지 선택 부분 border 설정
- 포켓몬 프로필 모달 모바일 사이즈 스타일 설정 및 다크모드 스타일링
-
> [List, Message] 세부 스타일링 설정

- src/components/button/Button.style.jsx
- src/components/navigationBar/NavigationBar.style.jsx
- src/pages/list/ListPage.style.jsx
- src/pages/list/index.jsx
- src/pages/post-to/PostToPage.style.jsx
- src/pages/post-to/components/post-to-card/Card.style.jsx
- src/pages/post/components/postCard/DeleteButton.style.jsx
- 메인페이지, 포스트 페이지 공용 버튼에서 커서 포인터 설정, 호버, 액티브 , 포커스 상태를 피그마 시안과 같은 디자인으로 설정했습니다
- post 페이지 삭제 버튼 , 페이지 삭제버튼 ,저장하기 버튼 스타일링 통일, 호버 , 액티브, 포커스 상태 설정
- 다크모드 버튼 호버 상태 스타일링
- post-to 페이지에서 모든 버튼에 커서 포인터값을 적용했습니다
> [post, post-to, main] 공용 버튼 컴포넌트 호버, 액티브, 포커스 상태 스타일링 및 세부 스타일링

- src/components/button/Button.style.jsx
- src/pages/list/ListPage.style.jsx
- src/pages/list/index.jsx
- src/pages/main/MainPage.style.jsx
- src/pages/main/index.jsx
- src/pages/post-to/components/profile/PokemonProfileModal.jsx
- src/pages/post-to/components/profile/Profile.jsx
- src/pages/post-to/components/profile/Profile.style.jsx
- src/pages/post/components/HeaderShareButton/HeaderShareButton.jsx
- 버튼 스타일링 수정
- 포켓몬 모달 버튼 모바일 사이즈 스타일링
- 메인 페이지 버튼 a 태그 안에 삽입
- 포켓몬 프로필 모달에서 모달이 아닌 부분 클릭시 모달이 닫히는 기능 추가
-
> [post, list] 버튼 , 포켓몬 모달 세부 스타일링 조정

- src/pages/post-to/components/profile/PokemonModalLoading.style.jsx
- src/pages/post-to/components/profile/PokemonProfileModal.jsx
- src/pages/post-to/components/profile/PokemonProfileModal.style.jsx
- 포켓몬 모달 작동 UI 변경 및 모바일 사이즈 스타일링
> [post-to] 포켓몬 모달 작동 UI 변경 및 모바일 사이즈 스타일링

- src/api/background-images/getBackgroundImages.js
- src/api/getRecipientList.js
- src/api/recipients/getRecipients.js
- src/api/recipients/postMessages.js
- src/api/recipients/postRecipients.js
- src/components/navigationBar/NavigationBar.jsx
- src/constant/list.js
- src/constant/url.js
- src/pages/list/ListPage.style.jsx
- src/pages/list/components/Card/Card.jsx
- src/pages/list/index.jsx
- src/pages/post-to/PostMessagePage.jsx
- src/pages/post-to/PostMessagePage.style.jsx
- src/pages/post-to/components/dropdown/Dropdown.style.jsx
- src/pages/post-to/components/post-to-card/CardList.jsx
- src/pages/post-to/components/wide-button/WideButton.jsx
- src/pages/post-to/index.jsx
- 네비게이션바 이름 변경 (롤링 -> 너글닿기)
- 변경 사항 없음
- 네비게이션 바 너비 수정
- api 폴더 분리해서 관리
- 색상 변수 분리해서 관리
- 엔터 키 눌렀을 때 제출 (메시지, 롤링페이퍼 만들기 모두)
- 함수 선언 위치 조정
[img]
-
>  [main, list, post-to] refactor 및 네비게이션바 이름 변경 (롤링 -> 너글닿기)

- src/pages/list/components/Card/Card.style.jsx
- src/pages/post/components/WriterImageBox/WriterImageBox.style.jsx
revert change about profile margin
> ⏪ 프로필 겹치게 하기

- src/pages/post/components/MostEmojiBox/MostEmojiBox.jsx
- Post 헤더에 이모지 증감이 적용되었을 때 스타일 변경이 제대로 되지 않던 문제 수정
- 당장 눈에 띄는 함수 고치느라 스타일 참조값은 변경못했네요 ;ㅅ; 변경했습니다.
> 🐛 이모지 등록 스타일이 다른 값을 참조하던 문제 수정

- src/Router.js
- src/pages/post-to/PostMessagePage.jsx
- src/pages/post-to/PostMessagePage.style.jsx
- src/pages/post-to/components/profile/Profile.style.jsx
- PostMessagePage 모바일 사이즈 스타일링
> [Post-to]💄 PostMessagePage 모바일 사이즈 스타일링

- src/pages/post-to/components/profile/PokemonProfileModal.style.jsx
- src/pages/post/components/RollingMessageModal/RollingMessageModal.style.jsx
> 💄 모바일 사이즈 깨지는 부분만 수정
